### PR TITLE
mickey develop

### PR DESCRIPTION
**Pull request by mickeytorres**
Peppy reporting for duty, y'all. 

The enemy AI, the asteroid tag still needs removed but there's a rotation for the asteroids in there if you want it @George-Machado if not I can't just delete it out. 

right now the enemies just move to the right side of the screen and don't stop moving. It's just a transform. 

I'm v tired.

### CODE REVIEW

**Comment by fulaniteDeTal** [comment]
ISSSSS GOOOOO

**Comment by penguincoco** [comment]
yeet

**Comment by mickeytorres** [comment]
Should be good to go now, need to add a Player tag to Fox's ship

**Comment by PPhive** [comment]
LGTM

**Pull request merged**
